### PR TITLE
(#1634) Updated Guide Card Overview Image on DS

### LINKED ISSUE #1634: CR: Update the Overview Image of Guide Card on NCIDS Documentation Site
### Request Description
Due to the update of the colors on NCIDS, the Overview Image on the Guide Card page on the NCIDS Documentation site has the wrong color displayed for the outline buttons on the card. This request is to create a new image with the correct color, and then to update the NCIDS Documentation Site with the new image.

### What's the expected change?
- Overview Image of the Guide Card on the NCIDS Documentation site is to be updated to have the correct color of the outline buttons

### What's the current functionality?
- The current Overview Image of the Guide Card on the NCIDS Documentation site has an outdated color of the outline buttons

### What's the updated acceptance criteria?
```gherkin
Scenario: A user visits the NCIDS Documentation site and views the Guide Card page
  Given as user is on the NCIDS Documentation site
    And the user is on the Guide Card Page under Components
    And they are viewing the Overview Image
  When the user views the Overview Image
  Then the color of the outline buttons of the card will match the current color (hex code: #298085)
```

### Additional details / screenshot
- Current Overview Image
image

- Updated Color Example
image

### Related Tickets
* Original Story Ticket #1479

### PR DESCRIPTION
**Pull request by blilianyu**
Closes #1634

### CODE REVIEW

**Comment by dcvijanovic1k** [comment]
Looks good - approved!

**Review by karlikpj — APPROVED** [review]

**Review by andyvanavery31 — CHANGES_REQUESTED** [review]
It looks like the new image was added but the old one wasn't removed and is still showing on the page. Could you please look into that?

**Comment by bennettcc** [comment]
Tagging @blilianyu just to make sure you see the feedback from Andy above ^^

**Comment by blilianyu** [comment]
@andyvanavery31 could you re-review please? it should be good to go

**Comment by blilianyu** [comment]
Redoing

**Pull request closed without merging**
