### PR TITLE
(#1396) Fix Code Block Line Wrap

### LINKED ISSUE #1396: Make sure content inside code block is visible
All content inside code block should be visible.

See image of content is being covered up by the copy code button:
image (1)

_Originally posted by @olitharp-nci in https://github.com/NCIOCPL/ncids/issues/1395#issuecomment-1810981389_

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #1396

### CODE REVIEW

**Comment by sarinapadilla** [comment]
@karlikpj I'm still seeing the overlap on smaller breakpoints:

* 560
  Screenshot 2024-01-29 at 10 26 58 AM

* 450
  Screenshot 2024-01-29 at 10 27 33 AM

Seeing this in Chrome, FF, and Safari on Mac.

**Comment by karlikpj** [comment]
@sarinapadilla updating padding in code-block to trigger wrapping at the specified breakpoints. Should be safe for mobile now.

**Comment by andyvanavery31** [comment]
@karlikpj I'm seeing the fix appearing for all instances where the displayed code has a way to break (e.g. a space), but for the lines that don't have an easy break this is still occurring at small breakpoints. See the last code snippet in Step 3 at <543px, and in the screenshot below. 
image

**Comment by andyvanavery31** [comment]
The update is fantastic! No further changes requested from me.

**Review by dlescarbeau — APPROVED** [review]

**Review by sarinapadilla — APPROVED** [review]
Looks great!

**Pull request merged**
