### PR TITLE
(#1822) Update Collections Title Patch

### LINKED ISSUE #1822: Update Collection item titles to visually be h3s following the nci-heading-h3 display
### Issue description
Collection item headings/links (e.g., `usa-collection__heading` need to be updated to have the same styling as the `nci-heading-h3` styling. This will update the font token from `xl`/24px to `md`/20px.

> **ESTIMATE** TBD

### What's the expected change?
- The Collection item headings/links use `nci-heading-h3` styling and display font token `md`/font size 20px.

### What's the current functionality?
- The Collection item headings/links use `nci-heading-h2` styling and display font token `xl`/font size 24px.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
Screenshot 2024-08-20 at 1 01 52 PM

### Technical notes
Our patch has 
```
@@ -39,12 +44,17 @@ .usa-collection__body {
 
 .usa-collection__heading {
   @include typeset($theme-collection-header-typeset);
-  @include u-margin-bottom(0);
+  @include u-margin-bottom(1);
   @include u-margin-top(0);
+
+	> .usa-link {
+		@include typeset-h2;
+    @include u-line-height('heading', 4);
+	}
 }
```

We should be setting `$theme-collection-header-typeset` should be enough to control the link size, so we should remove the `> .usa-link` selector. Currently in the patch, the collection header is set to `+$theme-collection-header-typeset: "heading", "lg", 3 !default;` which is the incorrect size. It should be updated to `+$theme-collection-header-typeset: "heading", "md", 3 !default;`

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #1822

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [x] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [x] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [x] Unit tests have been updated or created to reflect any javascript changes.
- [x] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [x] WCAG 2.1 Level AA requirements have been met.

### Development:
- [x] Any new or updated javascript code has 100% unit test coverage.
- [x] New or updated breakpoints have regression images.
- [x] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [x] There are no unexpected or unapproved regression image changes. 
- [x] Functionality of interactive elements meet the acceptance criteria.
- [x] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [x] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [x] Lighthouse: scores have not noticeably decreased during this PR.
- [x] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [x] New or updated features introduced in this PR are developed mobile-first.
- [x] Breakpoint changes and regression images match those breakpoints.
- [x] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

### CODE REVIEW

**Comment by andyvanavery31** [comment]
@karlikpj can you please update the titles to use Poppins Semi Bold on the Doc Site and on Storybook? Also, could you please add an updated overview image to the Doc Site page with an image supplied by @blilianyu or @monika-jaeger?

**Comment by monika-jaeger** [comment]
@karlikpj updated collections image here 
collecions-component sample

cc: @andyvanavery31 @blilianyu

**Comment by monika-jaeger** [comment]
@karlikpj version 2 of collections image
collecions-component sample

**Comment by monika-jaeger** [comment]
@karlikpj @andyvanavery31 version 3 of image added. This adjusted the numbered lines pointing to the resized fonts. 
cc: @blilianyu 
collecions-component sample

**Review by andyvanavery31 — APPROVED** [review]
Passes Product Review.

**Review by olitharp-nci — APPROVED** [review]

**Pull request merged**
