### PR TITLE
(#879) Color Luminance Spike

### LINKED ISSUE #879: Change usa-list storybook story to use Twig
### Subtasks
- [x] Create a shared template for usa-list
- [x] Change the usa-list storybook story to use that shared template

### LINKED ISSUE #978: Spike: Determine Luminance and Acceptable Colors for Links/Whole Site
### Expected Deliverables:
* Investigating changes to the luminance values to meet the AA and AAA a11y requirements
* If changes to luminance do not meet the requirements, investigate changing the colors chosen on the site to meet the a11y requirements

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #978

Working with color grades to correct contrast issue.

### CODE REVIEW

**Review by bennettcc — APPROVED** [review]

**Comment by bennettcc** [comment]
Both product team and ODDC feds reviewed and passed this PR

**Review by arcepaul — APPROVED** [review]

**Review by olitharp-nci — CHANGES_REQUESTED** [review]
Since the Input and Collections PR are in here, they should be added to Closed # in comments and should be in separate commits. 

I thought this PR would get rid of the theme notifications for banner and alert -- but still seeing them. Let's chat when everyone is back about that.

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
Links inside the informational alert are black. They should not be black.

**Review by olitharp-nci — APPROVED** [review]

**Review by monika-jaeger — APPROVED** [review]

**Review by bryanpizzillo — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]
passes wave, axeDevTool testing.  LGTM

**Pull request merged**
