### PR TITLE
(#496) Sidenav Icon Alignment

### PR DESCRIPTION
**Pull request by karlikpj**
Closes (#496)

### CODE REVIEW

**Review by laurelthrash — APPROVED** [review]
This passes product review on 08/17/22.

**Review by arcepaul — APPROVED** [review]

**Review by arcepaul — COMMENTED** [review]
Could you please update the stories to include cases where the link gets a wrapping link?

**Review by olitharp-nci — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
Hi Paul, can you please update the inner page template story to match the example site.

**Review by laurelthrash — APPROVED** [review]
Re-reviewed and approve the side nav (that includes the long title with wrapping).

**Review by bryanpizzillo — APPROVED** [review]

**Pull request merged**
