### PR TITLE
(#1587) Updates nci-header storybook with twig

### LINKED ISSUE #1587: Update storybook structure for nci-header
### `nci-header` storybook structure
1. Default (folder)
    1. English
    2. Spanish
3. Variants (folder)
    1. With Mega Menu (folder)
        1. English
        2. Spanish
4. Test cases (folder)
    1. Default (folder)
        1. No JS
        2. No Search Field
        3. Long Primary Link
        4. Two Item Navigation
        5. Too Many Items Navigation
    1. Logos (folder)
        1. CBIIT
        2. DCEG
        3. DCCPS
        4. MyPART
    1. Header with Mega Menu (folder)
        1. No JS
        2. Long Primary Button
        3. Long Mega Menu Content

Other tasks:
* Clean up all of the regressions (redundant breakpoint scenarios) associated with this component
* Create ncids-twig template
* Make sure scenarios still reflect all of the test cases that we have, but we do not need them as examples in the storybook structure

> **ESTIMATE** TBD

### Additional details / screenshot
- [Storybook structure wiki](https://github.com/NCIOCPL/ncids/wiki/Storybook-Structure)

### Related Tickets
* Parent ticket: #1224

### PR DESCRIPTION
**Pull request by dlescarbeau**
Closes #1587

### CODE REVIEW

**Review by sarinapadilla — CHANGES_REQUESTED** [review]
Please make these updates!
* Rename "Default" story to "Default English"
* Rename "Extended" folder to "Variants"
* Rename "Mega Menu English" story to "With Mega Menu English"
* Rename "Mega Menu Spanish" story to "With Mega Menu Spanish"
* Move the "Logos" folder and its stories into "Test Cases" > "Default" folder
* Rename "Extended with Mega Menu" folder to "Header with Mega Menu"
* Add a "No JS" story to the "Header with Mega Menu" folder
* Remove "Active Primary Link" and "Active Primary Button" stories

**Review by sarinapadilla — CHANGES_REQUESTED** [review]
Updated structure for these stories (discussed on Slack):

1. Default (folder)
    1. English
    2. Spanish
3. Variants (folder)
    1. With Mega Menu (folder)
        1. English
        2. Spanish
4. Test cases (folder)
    1. Default (folder)
        1. No JS
        2. No Search Field
        3. Long Primary Link
        4. Two Item Navigation
        5. Too Many Items Navigation
    1. Logos (folder)
        1. CBIIT
        2. DCEG
        3. DCCPS
        4. MyPART
    1. Header with Mega Menu (folder)
        1. No JS
        2. Long Primary Button
        3. Long Mega Menu Content

**Review by sarinapadilla — APPROVED** [review]
Looks good to me!

**Review by olitharp-nci — CHANGES_REQUESTED** [review]
- [ ] Twig: menu button text is hardcoded
- [ ] Twig: search button text is hardcoded
- [ ] Twig: mobile search button aria label is hardcoded
- [ ] Twig: mobile magnifying glass label text is hardcoded
- [ ] Default > Spanish: the search button is in English, see above. Use the translations found on [**the documentation site**](https://designsystem-dev.cancer.gov/develop/components/header/#aria-label-translations-table)
- [ ] Default header (without mega menu) navigation items should not have dropdown arrows indicating there is a mega menu. They should be links.

Requesting review from Sarina again since the regression images will all change.

**Review by sarinapadilla — APPROVED** [review]
Looks good with the changes that Olivia requested!

**Comment by olitharp-nci** [comment]
See changes here made for quick merge: https://github.com/NCIOCPL/ncids/compare/70c81c64bb178e33a2c07527a2cd0561ce3da914..7902437a6511a3b6565618cbed569d00cb6e589e
* The "no js" stories were definitely loading javascript. This has been fixed.
* Ran prettier on storybook files again. The linter will be added when storybook is updated to avoid this issues in the future.

**Review by olitharp-nci — APPROVED** [review]

**Pull request merged**
