### PR TITLE
(#1332) updates heading sizes for h3 h4 h5

### LINKED ISSUE #1332: NCIDS Documentation Site Increase Visual Distinction Between H2 and H3
### Change Request
Request is to increase the visual distinction between H2 and H3 on the NCIDS Documentation Site. This may be able to be fixed by implementing the new nci-headings component being built in R2.3.

### What's the expected change?
- There will be greater visual distinction between H2 and H3 on the NCIDS Documentation Site.

### What's the current functionality?
- The H2 and H3 on the NCIDS Documentation Site are very similar.

### Requirements

For consistency across Cgov and DS site, the changes shall be:
- change h3 to 20px (md)
- change h4 to 18px (sm)
- change h5 to 16px (xs)
- change N&E landing page heading label from h3 to h2
- change on prod h2 23px to 24px (xl)
- Align font sizes in Cancer.gov and identify unique cases (e.g., Related Resources) and bring to the Product and Design team to make a determination on these cases

### Notes

Here is the Buttons page mocked up with the proposed h3 size: https://www.figma.com/file/C1Enki5evIhPZg95weS6rW/NCI-Headings-(H1-H6)?type=design&node-id=2729%3A2256&mode=design&t=x0IVarxZ1XtosNYK-1.

The following component/styles will be affected:

- NCI Heading Styles & Modifiers - update h3, h4 and h5 sizes
- Paragraph Styles in Figma (no change on DS site)
- Collections component - update in the DS to change h3 label to h2
- News and Events page in production - utilizes the headings style (mentioned above) so the labels will change to the H2 size on Collections & Right side bar

### Related Tickets
* Original Story Ticket #1150

### PR DESCRIPTION
**Pull request by dlescarbeau**
- updates headings for h3, h4, and h5 (h3: `'lg' -> 'md'`) (h4: `'md' -> 'sm'`) (h5: `'sm' -> 'xs'`)
- updates Collections to use h2 rather than h3

Closes #1332

### CODE REVIEW

**Comment by blilianyu** [comment]
Looks great on my end!!

**Comment by blilianyu** [comment]
Looks great!!

**Comment by bennettcc** [comment]
This was approved by Federal team on 3/8

**Review by sarinapadilla — APPROVED** [review]
Looks good!

**Pull request merged**
