### PR TITLE
(#1422) Remove Background Color from Small Button

### LINKED ISSUE #1422: Remove background color from the small button
Remove background color from the small button. The small size modifier should only make the button small. Color should be applied with a color modifier. 

This would be a breaking change for the button component.

Usage to recreate the same button:

```diff
- <a class="usa-button usa-button--nci-small>Button</a>
+ <a class="usa-button usa-button--nci-small usa-button--secondary>Button</a>
```

This will additionally affect the banner component language toggle. We need to decide if we want to update the banner component html and css to extend the correct classes with a custom button or expect users to correct the markup when updating packages. (That probably answered the question.)

```diff
// breaking change
- <a href="/espanol" id="lang-toggle" class="usa-button usa-button--nci-small" hreflang="es">Español</a>
+ <a href="/espanol" id="lang-toggle" class="usa-button usa-button-nci-small usa-button--secondary" hreflang="es">Español</a>
```

or
```diff
// backwards compatible 
- <a href="/espanol" id="lang-toggle" class="usa-button usa-button--nci-small" hreflang="es">Español</a>
+ <a href="/espanol" id="lang-toggle" class="usa-button" hreflang="es">Español</a>
```

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #1422

### CODE REVIEW

**Comment by andyvanavery31** [comment]
Looks good to me!

**Review by bennettcc — APPROVED** [review]

**Comment by bennettcc** [comment]
Approved = product reviewed during the week of 2/5

**Comment by blilianyu** [comment]
So I see that the background color was removed but when I go to apply the `usa-button--nci-small` to Accent warm button, the secondary button color shows. 
Screenshot 2024-02-12 at 1 55 33 PM

Additionally, if I add `usa-button--accent-warm` to NCI Small button, the color doesn't change. 
Screenshot 2024-02-12 at 2 04 34 PM

Or this should happen once it's merged?

**Comment by karlikpj** [comment]
@blilianyu this is as expected / if you review the code-patch we have a backwards compatible fix so we don't have to update the cgov HTML sites yet (but at when we release the 3.0 update - it will be removed and that example you're trying will work)

**Comment by blilianyu** [comment]
@karlikpj ok perfect, thanks for the refresher! Looks good otherwise.

**Review by sarinapadilla — APPROVED** [review]
Looks good!

**Review by olitharp-nci — APPROVED** [review]

**Pull request merged**
