### PR TITLE
(#1584, #1673) Change back to top to init on scroll; add js and organizes footer stories

### LINKED ISSUE #1584: Update storybook structure for usa-footer
### `usa-footer` storybook structure
**Note**: NCI Big is our default, so we do not have a default folder

* 📁 Variants
  * 📁 NCI Big
    *  English
    * Spanish
  * 📁 Test Cases
    * No JS
    * Back to top
    

**Notes:** 
1. Test case > No JS: The back to top before it any javascript is initialized 
2. Test case > Back to top: The footer with lorem ipsum to add height to the viewport. This would allow us to do an onscroll to enable the back to top visibility.
3. NCI Big > English/Spanish would not show a back top top as it would not be the "scrolling" behavior. 

Other tasks:
* Clean up all of the regressions (redundant breakpoint scenarios) associated with this component
* Create ncids-twig template
* Make sure scenarios still reflect all of the test cases that we have, but we do not need them as examples in the storybook structure
* Clean up usa-footer > usa-error-message styles inside of the footer stylesheet and make use of `usa-error-message--nci-inverse` class
* And again, confirm there are no utility classes in the footer html, again.

> **ESTIMATE** TBD

### Additional details / screenshot
- [Storybook structure wiki](https://github.com/NCIOCPL/ncids/wiki/Storybook-Structure)

### Related Tickets
* Parent ticket: #1224

### LINKED ISSUE #1673: Hide back to top on load
While working on #1584, we've discovered bugs with the back to top component that blocks the ability to complete the ticket.

On load, the back to top link will appear and transition away. This element should not be visible until scroll.

https://github.com/NCIOCPL/ncids/assets/85901679/e0a000b4-be99-44e0-ba56-5baf83201b44

## Tasks

- [ ] Remove back to top from html, add back to top to the DOM once the footer is initialized.
- [ ] Back to top fades in on scroll.
- [ ] The HTML is updated in the:
   - [ ] Documentation site
   - [ ] Storybook
   - [ ] Example site
- [x] A new ticket is created to update the guidance for the footer: #1674

### PR DESCRIPTION
**Pull request by dlescarbeau**
- Closes #1584 
- Closes #1673

### CODE REVIEW

**Review by olitharp-nci — APPROVED** [review]

**Review by sarinapadilla — APPROVED** [review]
Looks good to me!

**Review by olitharp-nci — CHANGES_REQUESTED** [review]
> * documentation needs to be added for how to get a back to top without javascript
> * html needs to be updated _everywhere_
> * the following AC in the ticket were not done:
>    * Clean up usa-footer > usa-error-message styles inside of the footer stylesheet and make use of usa-error-message--nci-inverse class
>    * And again, confirm there are no utility classes in the footer html, again.
> 
> @sarinapadilla I removed your check since we have missing items from the AC. Will need to re-review. We'll get something pushed up soon.
> 


These items have been moved to https://github.com/NCIOCPL/ncids/issues/1701

**Comment by bryanpizzillo** [comment]
@olitharp-nci I am refactoring the footer-back-top-top.ts file as nci-big-footer.component.ts should NOT be creating the DOM elements. It should also not register 2 scroll handlers. We also should be able to not add the back to top -- for the documentation site. Dunno what another use case would be, but there is no easy way to hack it out I can't see.

**Comment by sarinapadilla** [comment]
I'm still seeing the back to top init on load of the documentation site.

https://github.com/NCIOCPL/ncids/assets/24591940/ca21c4ac-f6e1-4396-9c4e-44a632bdfb69

**Review by sarinapadilla — APPROVED** [review]
Jk, I've been told that the documentation site will be updated with #1701. So this looks good!

**Review by olitharp-nci — APPROVED** [review]

**Pull request merged**
