### PR TITLE
(#1398) NCIDS Summary Box

### LINKED ISSUE #1398: Story: Update usa-summary-box to Match NCI Design
### Requirements

**Single Summary Box**
- The usa-summary-box component will be patched to match the comp (see below)
- The usa-summary-box class name will be kept
- It will span the width of the container that it is in

**2 Summary Box Row Pattern**
- The usa-summary-box will be able to be put into a two-column pattern
- Each usa-summary-box will span the column that it is in
- The spacing between the usa-summary-boxes shall match the standard column spacing on the site

### Notes
- This ticket will build both the single usa-summary-box, and it will build the 2 Summary Box Row Pattern

### DoR DS Tasks

- [x] Update design of usa-summary-box to make the 'Call-Out Box' variant the default, and remove the USWDS version. Put the solution into its own class space on Figma
- [x] Refine user story statement
- [x]  Create Scenarios
- [x] Internal Review of Scenarios
  - [x] Design Approval
  - [x] Development Approval
  - [x] IA Approval
- [x]  Internal review of any changes to the Design solution for usa-summary-box on Figma
- [x]  Internal review of DS AC's (Development, Design, IA, QA)

### DoD DS Tasks

- [ ] Develop DS class from design Figma comp
  - [ ] Update Documentation Site
    - [x]  Draft the guidance and all sections necessary for usa-summary-box component to be added to Components on the NCIDS Documentation Site. #1410 
    - [x] Draft the guidance and all sections necessary for the 2-Summary Box Row to be added to Patterns on the NCIDS Documentation Site. See link in Resources for 
  - [ ]  Update Storybook Site
  - [ ]  Update Example Site
- [ ]  Internal review of the DS solution
- [ ]  Demo DS solution to client

### Prerequisites

- [x] Complete #1479  prior to starting this development

### Resources
- [Summary Box Mockup](https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCIDS-Design-Kit---Master?type=design&node-id=3993-10947&mode=design&t=jCATWGrfOrBfqLLk-0)
- [Cancer Types Mockup](https://www.figma.com/file/ZIgPLcQOlHYrbUxeWYaanZ/Cancer-Types?type=design&node-id=0-1&mode=design&t=sjEDA6k76dLlXTHe-0)
- [Scenarios](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.3/Development%20Scenarios/NCI%20Summary%20Box%20Scenarios.docx?d=wf0fdc099bda744a891acf8d6f437d2a9&csf=1&web=1&e=ayNnPv)
- [usa-summary-box Documentation Site Content](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B71C03BD3-1D50-414B-9BBC-7CA76E88B5DE%7D&file=Summary%20Box.docx&action=default&mobileredirect=true)
- [2-Summary Box Row Pattern Documentation Site Content](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7BDFE2D247-934B-4ECC-9A87-07DE150AC180%7D&file=Summary%20Box%20Row.docx&action=default&mobileredirect=true)

### Acceptance Criteria

**Single Summary Box Design Style**
```gherkin
Scenario: A user views a page with a usa-summary-box component
  Given a page editor has added a usa-summary-box component to the page
    And the usa-summary-box component has been patched and implemented in the Design System
  When the user views a page with a usa-summary-box component
  Then the usa-summary-box will match the Default version on the comp (see link in the Requirements section)
  When the user adds a usa-summary-box component to a page
  Then the user can add raw html to the summary box
  When the user adds hyperlinks to the summary box
  Then the hyperlinks will redirect the viewer to the linked page
```

**2-Summary Box Pattern**
```gherkin
Scenario: A user views a page with a 2-Summary Box Row pattern
  Given a page editor has added two usa-summary-box components to the page in the row pattern
    And the usa-summary-box component has been implemented in the Design System
  When the user views a page with the 2-Summary Box Row pattern
  Then the 2-Summary Box Row pattern will match the Summary Box Row on the comp (see link in the Requirements section)
  When the user adds a 2-Summary Box Row pattern to a page
  Then each usa-summary-box will match the functionality of the single usa-summary-box as listed in the above Acceptance Criteria
```

### PR DESCRIPTION
**Pull request by dev-rana-publicis**
Closes #1398

### CODE REVIEW

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
There should be no css for a summary-box row. You can only use existing USWDS layout items.

**Comment by olitharp-nci** [comment]
## Solutioning

For Storybook and the documentation site (including the guidance) we do not want to continue adding unnecessary packages for making equal-height, 2/3/4/etc row when this can be done using appropriate flex classes to the parent. By enabling flex utility classes, we can achieve this with:

```html
<div class='grid-container'>
 <div class='grid-row grid-gap-2 flex-row flex-align-stretch'>
  <div class='tablet:grid-col-6 display-flex flex-align-stretch'>
   <div class="usa-summary-box">...</div>
  </div>
  <div class='tablet:grid-col-6 display-flex flex-align-stretch'>
   <div class="usa-summary-box">...</div>
   </div>
 </div>
</div>
```

For this to work with cgov, we will need to turn on the flex utility classes. This will increase the file size by approximately .35kb. 

Utility module name | Class base | Gzip size | Default full size
-- | -- | -- | --
flex | flex- | 0.06 KB | 0.33 KB
flex-direction | flex- | 0.02 KB | 0.1 KB
flex-wrap | flex- | 0.02 KB | 0.1 KB

- [ ] We will eventually want to go back and retro-fit this for the card components.
- [ ] We will need to update the guidance for the summary box pattern page.

**Comment by blilianyu** [comment]
The updates look good to me!

**Review by olitharp-nci — APPROVED** [review]

**Comment by andyvanavery31** [comment]
Looks good to me. Will add the checkmark once we receive client approval.

**Comment by blilianyu** [comment]
Updates look great!

**Review by bryanpizzillo — APPROVED** [review]

**Review by blilianyu — APPROVED** [review]
Product & client approved

**Pull request merged**
