### PR TITLE
(#1761) Update 'Applying other utilities' paragraph on Figma Guide

### LINKED ISSUE #1761: Update 'Applying other utilities' paragraph on Figma Guide page on Doc Site
### Issue description

Update copy on the doc site on the [Figma Guide](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide) page under the paragraph heading "[Applying other utilities that are not added to the NCIDS Design Kit library](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide#applying-other-utilities-that-are-not-added-to-the-ncids-design-kit-library)" to add more clarity that border, border radius and outline are utilities that can only be referenced in Figma, especially when linking from other areas in the doc site.

> **ESTIMATE** TBD

### What's the expected change?
Update heading and paragraph to read:

> #### Border, Border Radius and Outline Utilities 
> Not all utilities are available in the NCIDS Design Kit Library, which appears on the right-hand sidebar when you are designing a composition or prototype. Reference the [Tokens and Utilities](https://www.figma.com/community/file/1288512334920909770/ncids-design-kit) page in our Figma file to learn how to apply border, border radius and outline utilities to your designs.

### What's the current functionality?
Current heading and paragraph reads:

> #### Applying other utilities that are not added to the NCIDS Design Kit library
> On the Tokens and Utilities page you will see other utilities you can apply that are not added to the NCIDS Design Kit Library on the right-hand side bar when you are designing a composition or prototype. Border, border radius and outline are all utilities that can be referenced on this page on how to apply these styles to your designs.

### What's the updated acceptance criteria?
The copy is updated per the expected change.

### Related Tickets
* This came out of discussions from PR Ticket #1751

### PR DESCRIPTION
**Pull request by monika-jaeger**
Closes #1761

## Pull Request Details

This updates the copy on the doc site on the [Figma Guide](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide) page under the (former) paragraph heading "[Applying other utilities that are not added to the NCIDS Design Kit library](https://designsystem-dev.cancer.gov/develop/get-started/figma-guide#applying-other-utilities-that-are-not-added-to-the-ncids-design-kit-library)" to add more clarity that border, border radius and outline are utilities that can only be referenced in Figma, especially when linking from other areas in the doc site.

_Note: The heading is now **"Border, Border Radius and Outline Utilities"**_

Closes ##1761

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [x] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [x] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [x] Unit tests have been updated or created to reflect any javascript changes.
- [x] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [ ] WCAG 2.1 Level AA requirements have been met.

### Development:
- [ ] Any new or updated javascript code has 100% unit test coverage.
- [ ] New or updated breakpoints have regression images.
- [ ] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [ ] There are no unexpected or unapproved regression image changes. 
- [ ] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [ ] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [ ] Lighthouse: scores have not noticeably decreased during this PR.
- [ ] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [x] New or updated features introduced in this PR are developed mobile-first.
- [x] Breakpoint changes and regression images match those breakpoints.
- [x] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

### CODE REVIEW

**Comment by blilianyu** [comment]
@monika-jaeger can you change the link for "Token & Utilities" to the permalink https://www.figma.com/design/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?node-id=3917-6868&t=YVntX6mh1NZavZkA-1?

**Comment by monika-jaeger** [comment]
@blilianyu updated the link for Tokens and Utilities, and set privacy settings to Anyone in the Figma Community File. Ready for re-review!

**Comment by blilianyu** [comment]
@monika-jaeger Looks great, thank you!!

**Review by blilianyu — APPROVED** [review]

**Review by sarinapadilla — APPROVED** [review]
Looks good!

**Pull request merged**
