### PR TITLE
(#1302) Update Figma Links in DocSite

### LINKED ISSUE #1302: Update Figma Links to Direct Location on NCIDS Documentation Site
### Change Request
Request to update the Figma links on the NCIDS Documentation site to link to the specific sections of the Figma instead of linking to the Figma's homepage.

### What's the expected change?
- Links on NCIDS Documentation Site to Figma will go to the specific component/class/section instead of always going to the Figma homepage.

### What's the current functionality?
- All Figma links on the NCIDS Documentation Site will go to the Figma homepage.

### Solution
- Create a base url for the Figma file that is respective to its version that can be taken with /* to the individual components on the Figma

### Additional details / screenshot
The following list are of all the locations on the Documentation Site that need to be updated with the location on the Figma, followed by the component on Figma. The locations are listed as L1 > L2 > L3 etc.

Updated links:
| Page | Updated link |
|---|---|
| Foundations > Typography > Headings > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5294%3A10398&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Autocomplete > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A39978&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Banner > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A39899&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Breadcrumb > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A39866&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Button > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5314%3A9664&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Card > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A38952&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Collection > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A38604&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > CTA Strip > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A42672&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Footer > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7991&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Guide Card > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7481&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Header > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A45831&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Hero > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A45414&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Promo Block > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5322%3A6243&mo"de=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Side Navigation > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A44558&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Site Alert > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A44496&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > Skipnav > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A44701&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Templates > 3-Card Row > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5280%3A38952&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Templates > Guide Card Row > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5321%3A7481&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Templates > Summary Box Row > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5469%3A8156&mode=design&t=9xNemHVdk0y2K4UA-1 |

### Resources
https://www.figma.com/file/ZIgPLcQOlHYrbUxeWYaanZ/Cancer-Types?type=design&version-id=4994908981&node-id=715-3392&mode=design&viewport=3699%2C126%2C1.16&t=D26katiZkkoP1Ce4-0

https://help.figma.com/hc/en-us/articles/360038006754-View-a-file-s-version-history

https://www.figma.com/developers/api#version-history

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #1302

### CODE REVIEW

**Comment by blilianyu** [comment]
@karlikpj Can you also update the following pages?

| Page | Updated link |
|---|---|
| Components > Header > Megamenu > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5281%3A45831&mode=design&t=lGwrxbWFW3JAwAet-1 |
| Components > List > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5295%3A10469&mode=design&t=9xNemHVdk0y2K4UA-1 |
| Components > Summary Box > "View in Figma" | https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=5469%3A8156&mode=design&t=9xNemHVdk0y2K4UA-1 |

cc: @dcvijanovic1k

**Review by dcvijanovic1k — COMMENTED** [review]
Thumbs up from Lilian and myself - good to go!

**Comment by blilianyu** [comment]
Updates look great!

**Review by sarinapadilla — APPROVED** [review]
Updates look good!

**Review by olitharp-nci — APPROVED** [review]

**Pull request merged**
