### PR TITLE
(#833) Fixed bad html in promo block examples and stories

### LINKED ISSUE #833: Fix wonky HTML in promoblocks code
Go through promoblocks code and fix some of the wonky things found while implementing promoblocks templates for CGDP.
Examples in storyblook and example site page
- remove link around images to match cgdp
- incorrectly supplied `alt` attributes in `<button>` and `<a>` links
- sections with unsupported `label` attributes

> **2**

### LINKED ISSUE #846: Fix html issues raised by validator on example site
Validate any glaring issues on the example site and make sure that the bad html has not made it's way into the storybook stories.

> **2** 

### What's the expected change?
HTML validation should not raise any major errors

### Related Tickets
* #833

### PR DESCRIPTION
**Pull request by arcepaul**
Closes #833 .
Closes #846 .

Used HTML validator to fix up some bad html that made its way in.
- removed labels from sections
- removed alt tags from buttons and links
- removed hrefs from buttons

Validator used: 
https://validator.w3.org/

Screenshot 2023-03-31 at 9 11 04 AM

### CODE REVIEW

**Comment by arcepaul** [comment]
Using the validator (https://validator.w3.org/) you can input the urls above to see the report.  Please let me know if there are any errors I may have missed.

If you want to see the BEFORE use https://designsystem-dev.cancer.gov/develop/example-site/

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
@arcepaul can you also try https://validator.w3.org/nu/? A bunch of the validators used in CI/CD is based on nu.

**Comment by arcepaul** [comment]
> @arcepaul can you also try https://validator.w3.org/nu/? A bunch of the validators used in CI/CD is based on nu.

That is the validator I used.  The w3 one I linked switches over to Nu once you enter the code to be validated.

**Review by olitharp-nci — APPROVED** [review]

**Comment by arcepaul** [comment]
Closing having been replaced by #896

**Pull request closed without merging**
