### PR TITLE
(#1841) Adds robots txt file

### LINKED ISSUE #1841: CR: Make the Example Site, Past Releases, and Search Pages Not Show Up on Search Results for Google and Site Wide Search
### Request Description
This request is to create Robots.txt so that cetain pages do not get indexed for by Google nor by the Site Wide Search
* This should match anything that is `/example-site` `/past-releases', `/search`

### What's the expected change?
- Update search for Google and Site Wide Search so that example site, past releases, and search pages do not get indexed by Google nor the Site Wide Search

### What's the current functionality?
- Example site, past releases, and search pages are being indexed by Google and the Site Wide Search

### PR DESCRIPTION
**Pull request by dlescarbeau**
Closes #1841

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [x] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [x] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [x] Unit tests have been updated or created to reflect any javascript changes.
- [x] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [x] WCAG 2.1 Level AA requirements have been met.

### Development:
- [x] Any new or updated javascript code has 100% unit test coverage.
- [x] New or updated breakpoints have regression images.
- [x] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [x] There are no unexpected or unapproved regression image changes. 
- [x] Functionality of interactive elements meet the acceptance criteria.
- [ ] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [x] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [x] Lighthouse: scores have not noticeably decreased during this PR.
- [x] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [x] New or updated features introduced in this PR are developed mobile-first.
- [x] Breakpoint changes and regression images match those breakpoints.
- [x] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

### CODE REVIEW

**Comment by bennettcc** [comment]
Per 9/25 standup, the sitewide search PR should be merged in ahead of this robots.txt PR: https://github.com/NCIOCPL/ncids/pull/1846

**Review by bryanpizzillo — COMMENTED** [review]
If this shows up on the develop site and is a properly formed robots.txt file, this passes code review. I will not approve ATM to not confuse people that it can be merged. Can approve once product gives the thumbs up.

**Comment by welshja** [comment]
Approved from the product side!

**Review by bennettcc — APPROVED** [review]

**Comment by bennettcc** [comment]
Added product checkmark - Joe approved on 10/11

**Pull request merged**
