### PR TITLE
(#1504) Margin and Padding Utility Page

### LINKED ISSUE #1504: CR: Adopt Documentation Site Padding and Margin Page to NCIDS Ownership
### Request Description
This change request is to fully adopt the margin and padding utilities on the doc site from being a pointer to USWDS to our full ownership. This change will require:

- [x] First and foremost, we need to update the left nav to say "Margin and Padding". We also need to update the URL to be /margin-padding!
- [x] IA/development/design updates to the [doc site page](https://designsystem-dev.cancer.gov/develop/foundations/spacing-units/padding-margin) with all content needed using the new utility page template (created in #1593)
- [ ] Design updates to the [community Figma](https://www.figma.com/file/4FeMfprVErO6esR8FLczp5/NCIDS-Design-Kit?type=design&node-id=0-1&mode=design&t=Ec8CKPLUg3f7Jlm4-0)
- [x] Developer updates to the code to adopt the margin and padding utilities within the NCIDS

### What's the expected change?
- The doc site is updated to show users how to fully use margin and madding utilities without pointing to USWDS
- The community Figma file will be updated to include the margin and madding utilities
- The NCIDS code will be updated to fully adopt the margin and padding utilities

### What's the current functionality?
- The doc site directs users to USWDS [Margin and Padding](https://designsystem.digital.gov/utilities/margin-and-padding/) utility page

### Related Tickets
* **Prerequisite:** #1593 
* Original Story Ticket #1208 
* Original PR #1257
* Related Ticket #934  

### Notes
Margin:
* `margin-horizontal` will need to be split into three different tables for 'margin/margin bottom`. 'margin/margin top`, and 'margin/margin top and bottom`
* `margin-vertical` will need to be split into three different tables for 'margin/margin bottom`. 'margin/margin top`, and 'margin/margin top and bottom`

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #1504

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [x] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [x] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [x] Unit tests have been updated or created to reflect any javascript changes.
- [x] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [x] WCAG 2.1 Level AA requirements have been met.

### Development:
- [x] Any new or updated javascript code has 100% unit test coverage.
- [x] New or updated breakpoints have regression images.
- [x] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [x] There are no unexpected or unapproved regression image changes. 
- [x] Functionality of interactive elements meet the acceptance criteria.
- [x] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [x] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [x] Lighthouse: scores have not noticeably decreased during this PR.
- [x] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [x] New or updated features introduced in this PR are developed mobile-first.
- [x] Breakpoint changes and regression images match those breakpoints.
- [x] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [ ] New code passes code quality standards set by industry standards.
- [ ] The expected Storybook stories have been added or updated for the new or updated feature.
- [ ] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [ ] VoiceOver: Described content matches with what was expected.
- [ ] Keyboard navigation: new or updated features and content are navigable via the keyboard.

### CODE REVIEW

**Comment by bryanpizzillo** [comment]
## Viewing Information
  * [The documentation site](https://designsystem-dev.cancer.gov/pr-1767/)
  * [NCIDS JS Documentation](https://designsystem-dev.cancer.gov/pr-1767/ncids-js/)
  * [The storybook site](https://designsystem-dev.cancer.gov/pr-1767/storybook/)
  * [The example site](https://designsystem-dev.cancer.gov/pr-1767/example-site/)

**Comment by andyvanavery31** [comment]
This looks good to me!

**Review by bennettcc — APPROVED** [review]

**Comment by bennettcc** [comment]
Product reviewed and approved on 7/3

**Review by bryanpizzillo — APPROVED** [review]
Code looks good to me.

**Pull request merged**
