### PR TITLE
(#1591) Updates usa-sidenav storybook content

### LINKED ISSUE #1591: Update storybook structure for usa-sidenav
### `usa-sidenav` storybook structure
1. Default (folder)
    1. Default
        * This example will display levels [Hadouken](https://en.wikipedia.org/wiki/Hadouken)-style:
hadoukensidenav

2. Test Cases (folder)
    1. L1 Long Titles
    2. Cancergov Full

Other tasks:
* Clean up all of the regressions (redundant breakpoint scenarios) associated with this component
  * Keep at least one scenario that tests the side nav disappearing on mobile
* Create ncids-twig template
* Make sure scenarios still reflect all of the test cases that we have, but we do not need them as examples in the storybook structure
* Remove `--nci-sidenav` from `usa-sidenav` from digital platform: https://github.com/NCIOCPL/cgov-digital-platform/issues/4268

> **ESTIMATE** TBD

### Additional details / screenshot
- [Storybook structure wiki](https://github.com/NCIOCPL/ncids/wiki/Storybook-Structure)

### Related Tickets
* Parent ticket: #1224

### PR DESCRIPTION
**Pull request by dlescarbeau**
Closes #1591

### CODE REVIEW

**Review by andyvanavery31 — CHANGES_REQUESTED** [review]
Can you please add the Cancergov Full story (see the Wiki) to the Test Cases folder and please add the regression images for that story? The other regression images look good.

**Comment by sarinapadilla** [comment]
@dlescarbeau, the hadouken labels are a bit off. Each level should reflect which one it is, with the expanded items still being the same level as the not expanded. Also, need the child items that close up the side nav.
It'll be like this:
```
Level 1
Level 1 Expanded
    Level 2
    Level 2 Expanded
        Level 3
        Level 3 with Children
        Level 3 Expanded
            Level 4
            Level 4 Expanded
                Level 5
                Level 5 Expanded
                    Level 6
                Level 5
            Level 4
        Level 3
    Level 2
Level 1
```

I do like the idea of having other items that have children that aren't expanded like you did with one of the level 3 items, so I added that to the above display and I'll update the hadouken image on the ticket!

**Comment by sarinapadilla** [comment]
@dlescarbeau There will need to be another update for the long title test case. It has the same numbering issue as the default had, and no closing hadouken, so here's what it needs to be updated to:

```
Level 1 with a super long title for testing purposes
    Level 2 with a super long title for testing purposes
    Level 2 with a super long title for testing purposes
        Level 3 with a super long title for testing purposes
        Level 3 with a super long title for testing purposes
            Level 4 with a super long title for testing purposes
            Level 4 with a super long title for testing purposes
                Level 5 with a super long title for testing purposes
                Level 5 with a super long title for testing purposes
                    Level 6 with a super long title for testing purposes
                Level 5 with a super long title for testing purposes
            Level 4 with a super long title for testing purposes
        Level 3 with a super long title for testing purposes
    Level 2 with a super long title for testing purposes
Level 1 with a super long title for testing purposes
```

**Review by andyvanavery31 — APPROVED** [review]
Looks good to me!

**Pull request merged**
