### PR TITLE
(#1498) Update Header for NCI Variants

### LINKED ISSUE #1498: Update header to support renamed variants
In our usage we have moved towards having 2 variants for the header. A [default](https://designsystem-dev.cancer.gov/develop/components/header/#default-header) that has normal links in the primary nav, and one that has a [mega menu] (https://designsystem-dev.cancer.gov/develop/components/header/#nci-header-with-mega-menu-1).

This change request is to make the make the default component require no additional classes other than `nci-header`. Right now `<header class="nci-header">...</header>` looks like:
image

Additionally we should have `nci-header--mega-menu` as an new name for `nci-header--extended`. HOWEVER, we need both `nci-header--mega-menu` and `nci-header--extended` to work the exact same way. (This is so we can update the digital platform without causing breaking changes)

The documentation site should be updated so the example HTML matches the correct classes. For now we have already updated the words.

In addition to the above changes, we would like to align the code of the nci-header more closely to USWDS, and possible update the html to actually use the usa- classes directly. (Possibly *lightly* patching them) If we cannot use the classes directly, can we extend them, so our scss is just wrappers around `@extend`.  
* Is it possible to use usa-nav instead of nci_navbar?
   * If we cannot just use the file, can we extend uswds styles? This makes it easier to see if USWDS has updated something we need to account for.
* Can we replace `nci-search` in lieu of `usa-search`? 
   * If we cannot just use the file, can we extend uswds styles? This makes it easier to see if USWDS has updated something we need to account for.

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #1498

### CODE REVIEW

**Comment by dcvijanovic1k** [comment]
Approved! Tested FF/Chrome/Safari

**Review by olitharp-nci — CHANGES_REQUESTED** [review]
There should be updated html reflecting these changes in the doc site, storybook, etc anywhere the header has been used.

**Comment by karlikpj** [comment]
We did not use/patch uswds search directly as our search button and input changes on tablet breakpoint and does not align with uswds's components. However we extend them in our scss to create this hybrid. 

We also didn't use the uswds primary navigation as theirs use accordions for functionality and some styling and would require patching to both.

**Review by sarinapadilla — APPROVED** [review]
Looks good!

**Review by olitharp-nci — APPROVED** [review]

**Pull request merged**
