### PR TITLE
(#1727) Update Foundations page with copy edit recommendations

### LINKED ISSUE #1727: Update Foundations page with copy edit recommendations
Please update the Foundations page with the updates listed in tracked changes from the copy edit review:

https://designsystem-dev.cancer.gov/develop/foundations/

Foundations document: https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7Ba777125a-00e2-4367-add5-1b0ef14d1795%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk_ns.bim&wdExp=TEAMS-CONTROL&wdhostclicktime=1717712444611&web=1

### PR DESCRIPTION
**Pull request by monika-jaeger**
## Pull Request Details

Updated the Foundations page with the updates listed in tracked changes from the copy edit review document.

Closes #1727

https://designsystem-dev.cancer.gov/pr-1733/foundations/

### CODE REVIEW

**Comment by blilianyu** [comment]
@monika-jaeger, under "What Are Utilities?", the semicolon after "element" needs to be changed to a comma.

**Review by blilianyu — APPROVED** [review]
Update looks great!

**Comment by bennettcc** [comment]
Header links go to a 404 - to be resolved by: https://github.com/NCIOCPL/ncids/issues/1747

**Comment by bennettcc** [comment]
Closing this PR - it is not needed. The needed changes are being added as part of https://github.com/NCIOCPL/ncids/pull/1770

**Pull request closed without merging**
