### PR TITLE
(#1839) Card font size change

### LINKED ISSUE #1839: CR: NCIDS Card Font Sizes for Consistency on NCIDS
### Request Description
The change to Cards has been approved by the client as of 26AUG2024. This request is to update the NCIDS Cards with the changes to the font. The result of the change will have the description text be token size xs (16px), the card title will be token size md (20px), and the group/row heading will be size xl (24px).

### What's the expected change?
- The NCIDS Cards will have their font styling updated so that the description text be token size xs (16px), the card title will be token size md (20px), and the group/row heading will be size xl (24px).
- The updates will be reflected on the NCIDS Documentation Site and the NCIDS Storybook.
- The overview image for NCIDS Cards and the template for the 3-Card Row will be updated with the correct font sizes
- Regression Images of these cards will be updated on NCIDS Storybook.

### What's the current functionality?
- NCIDS Cards have a description text size of 18px, card title text size of 22px, and group/row heading font size of 24px.

### What's the updated acceptance criteria?
```gherkin
Scenario: A site visitor views an NCIDS Feature Card component
  Given the site visitor is on the NCIDS Documentation Site or the NCIDS Storybook
    And the NCIDS Card font sizes have been updated
  When the visitor views the NCIDS Card
  Then the description text size of the card will be token size xs (16px)
    And the card title text size will be token size md (20px)
    And the card row heading text size will be token size xl (24px)
  When the visitor views the NCIDS Card on the 3-Card Row Page
  Then the description text size of the card will be token size xs (16px)
    And the card title text size will be token size md (20px)
    And the card row heading text size will be token size xl (24px)
```

### PR DESCRIPTION
**Pull request by karlikpj**
Closes #1839

## Pull Request Details

_Add description_

Closes #<TICKET-NUMBER>

## Author PR Checklist
Items that the author of the PR is responsible for checking before submitted the PR.

### General:
- [x] I have reviewed the acceptance criteria defined in the ticket and ensured the work has been completed.
- [x] The commit message passes [all quality commit message standards](https://github.com/NCIOCPL/ncids/wiki/Creating-Quality-Commit-Messages).
- [x] Unit tests have been updated or created to reflect any javascript changes.
- [x] Storybook scenarios have been updated or created to reflect any html/css/js changes.

### Accessibility:
- [x] WCAG 2.1 Level AA requirements have been met.

### Development:
- [x] Any new or updated javascript code has 100% unit test coverage.
- [x] New or updated breakpoints have regression images.
- [x] Breaking changes have been thoroughly documented in the PR.

## Product Reviewer PR Checklist
Items the product team is responsible for reviewing.

### General:
- [x] There are no unexpected or unapproved regression image changes. 
- [x] Functionality of interactive elements meet the acceptance criteria.
- [x] The product is visually and functionally the same across the different browsers.

### Accessibility:
- [x] AxeDev Tools: there are no new or outstanding accessibility issues introduced in this PR.
- [x] Lighthouse: scores have not noticeably decreased during this PR.
- [x] Wave: there are no new errors or contrast errors introduced in this PR.

## Design Reviewer PR Checklist
Items the design team is responsible for reviewing.  

### General:
- [ ] New or updated features introduced in this PR are developed mobile-first.
- [ ] Breakpoint changes and regression images match those breakpoints.
- [ ] This PR has been tested in all supported browsers at all breakpoints.

## Developer Reviewer PR Checklist
Items the development team is responsible for reviewing.

### General:
- [x] New code passes code quality standards set by industry standards.
- [x] The expected Storybook stories have been added or updated for the new or updated feature.
- [x] The expected unit tests have been added or updated for the new or updated feature.

### Accessibility:
- [x] VoiceOver: Described content matches with what was expected.
- [x] Keyboard navigation: new or updated features and content are navigable via the keyboard.

### CODE REVIEW

**Review by andyvanavery31 — APPROVED** [review]
Passes Product review.

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
I would like us to discuss this a bit more and bring some consistency to these token usages. I.E. We should have a `$theme-card-title` and `$theme-card-body` or something tokens and set them accordingly. This change in this PR (as of this writing) has now made these items out of sync with Guide Cards. However, we have a ticket in the platform saying, "The body text shall have the same font size as all cards from the Design System," **which is for a wide guide card.** This type of requirement would do better by referencing the theme token to use. (Figma too?)

CC: @andyvanavery31

**Comment by bryanpizzillo** [comment]
> I would like us to discuss this a bit more and bring some consistency to these token usages. I.E. We should have a `$theme-card-title` and `$theme-card-body` or something tokens and set them accordingly. This change in this PR (as of this writing) has now made these items out of sync with Guide Cards. However, we have a ticket in the platform saying, "The body text shall have the same font size as all cards from the Design System," **which is for a wide guide card.** This type of requirement would do better by referencing the theme token to use. (Figma too?)

@andyvanavery31 and I talked about this. The Guide Card component and the Card component should be kept separate. However, we should still have component theme tokens for the font sizes. Note my naming in the initial comment sucks. Funny enough, there are some tokens already in USWDS for cards. Probably a lot more than we need. https://designsystem.digital.gov/documentation/settings/#card.

**Comment by bryanpizzillo** [comment]
One more followup, WRT the token naming. 
So this has an odd issue - we "replaced" usa-card with nci-card. While we don't pass through usa-card at this point, we could in the future. If we reuse or name our tokens for nci-card to be `$theme-card` we will break or conflict with usa-card. So for this instance we should use `$theme-nci-card-*` for nci-card settings. There should be a nice comment above these settings pointing out that we are naming this `$theme-nci-card-` to avoid conflicts with usa-card in the future.

@karlikpj suggested `$theme-nci-card-title-typeset` and `$theme-nci-card-description-typeset` for the token names, which look good.

**Comment by andyvanavery31** [comment]
After the change to use `$thme-nci-card-title-typeset` and `$theme-nci-card-description-typeset`, this still passes Product Review.

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
@karlikpj can you please add to your comment that says `// NCI Card` and make it:
```
// NCI Card
// NOTE: We are including the component namespace (nci) for this theme token so as to not conflict with usa-card tokens. ($theme-card-X) Normally we would not except for the conflict. 
```

**Review by bryanpizzillo — APPROVED** [review]

**Pull request merged**
