### PR TITLE
(#1468) JS for accordion functionality

### LINKED ISSUE #1468: Story: Create JS for usa-accordion
### Requirements

- The js will be built to work with the css from the usa-accordion component from USWDS
- The js will allow the creator to indicate what the sections will be that will be reduced into the accordion headings
- The js will allow the creator to indicate what content will be hidden within the sections of the accordion
- The js will ensure that when the section is collapsed and the user clicks anywhere in the heading container, the section will expand
- The js will ensure that when the section is expanded and the user clicks anywhere in the heading container, the section will collapse
- The js will have an option that will allow the user to expand multiple sections at the same time. Opening multiple sections will be disabled as default
- The js will allow the option to have the first section will appear expanded, while all other sections will appear collapsed as the standard for its use, and this option will be active as default
- The js will allow nested accordions to function where, if the section containing another accordion is expanded, the internal accordion will follow the same rules as a stand alone accordion (first section will be expanded. Other section will be collapsed)
- If a user is viewing a url with an anchor fragment (i.e. #) we need to find that heading, or section those contents are in, and expand that section on init.
- The ncids-twig-template for this component will be created

### Notes
- Section is defined as heading + content

### DoR DS Tasks

- [x] Refine user story statement
- [x] Create scenarios
- [x] Internal Review of Scenarios
  - [x] Design Approval
  - [x] Development Approval
  - [x] IA Approval
- [x]  Internal review of DS AC's (Development, Design, IA, QA)

### DoD DS Tasks

- [ ] Develop DS class from design Figma comp
  - [ ] Update Documentation Site
    - [ ] Draft the guidance and all sections necessary for addition to the NCIDS for All Documentation Site. TIMING OF DOCUMENTATION COMPLETION TO BE DISCUSSED ON 10JAN2024.
    - [ ] Create page for the Accordion within the Components section
    - [ ] Update the list of components on the [main Components landing page](https://designsystem-dev.cancer.gov/develop/components/)
  - [ ] Update Storybook Site
  - [ ] Update Example Site (if needed)
- [ ]  Internal review of the DS solution
- [ ]  Demo DS solution to client

### Resources
- USWDS Documentation on usa-accordion https://designsystem.digital.gov/components/accordion/

### Scenarios
- **Storybook:** Under USWDS, Components, on the Accordion page, the JS will be updated to the solution from this ticket
   - We actually have 3 forms of HTML to support. (Noted in the technical section) The "Basic HTML" is what we should use for our default and variants. The other html tests should be under test cases.
   * 📁 Accordion
      * 📁 Default
         * Default
         * Default - multiselectable
      * 📁 Variants
         * 📁 Bordered
            * Bordered
            * Bordered - multiselectable
      * 📁 Test Cases
         * 📁 Basic HTML
            * Nested Example
            * No JS
         * 📁 Cancer.gov HTML
            * Sample article
            * Nested
            * No JS
         * 📁 USWDS†
            * <stories from USWDS storybook>
† USWDS may live in a different folder based on convos with @olitharp-nci 

### Acceptance Criteria

**Default Single Accordion**
```gherkin
Scenario: A user views a page with a usa-accordion component
  Given the js for the usa-accordion component has been created
    And the usa-accordion with the new js has been added to a page
  When the user views the usa-accordion component
  Then they will see the each section header displayed for the accordion
    And the first section will be expanded to display all of the hidden content
    And all other sections will be collapsed to hide the content within those sections
  When a user clicks on the heading container displayed for a collapsed section
  Then the section clicked will expand
  When a user clicks on the heading container displayed for an expanded section
  Then the section clicked will collapse
  When the user clicks on multiple collapsed section headers sequentially
  Then the clicked on section will expand
    And the previously expanded section will collapse
```

**Single Accordion with First Section Collapsed**
```gherkin
Scenario: A user views a page with a usa-accordion component
  Given the js for the usa-accordion component has been created
    And the usa-accordion with the new js has been added to a page
  When the user views the usa-accordion component
  Then they will see the each section header displayed for the accordion
    And all sections will be collapsed to hide the content within those sections
  When a user clicks on the heading container displayed for a collapsed section
  Then the section clicked will expand
  When a user clicks on the heading container displayed for an expanded section
  Then the section clicked will collapse
  When the user clicks on multiple collapsed section headers sequentially
  Then the clicked on section will expand
    And the previously expanded section will collapse
```

**Single Accordion with Multiple Expansions Allowed**
```gherkin
Scenario: A user views a page with a usa-accordion component with multiple expansions of sections allowed
  Given the js for the usa-accordion component has been created
    And the usa-accordion with the new js has been added to a page
  When the user views the usa-accordion component
  Then they will see the each section header displayed for the accordion
    And the first section will be expanded to display all of the hidden content
    And all other sections will be collapsed to hide the content within those sections
  When a user clicks on the heading container displayed for a collapsed section
  Then the section clicked will expand
  When a user clicks on the heading container displayed for an expanded section
  Then the section clicked will collapse
  When the user clicks on multiple collapsed section headers sequentially
  Then all clicked sections will expand sequentially
```

**Nested Default Accordions**
```gherkin
Scenario: A user views a page with a usa-accordion component nested within another usa-accordion
  Given the js for the usa-accordion component has been created
    And the usa-accordion with the new js has been added to a page nested in another usa-accordion
  When the user views the usa-accordion component
  Then they will see the each section header displayed for the accordion
    And the first section will be expanded to display all of the hidden content
    And all other sections will be collapsed to hide the content within those sections
  When a user clicks on the heading container displayed for a collapsed section
  Then the section clicked will expand
  When a user clicks on the heading container displayed for an expanded section
  Then the section clicked will collapse
  When the user clicks on multiple collapsed section headers sequentially
  Then the clicked on section will expand
    And the previously expanded section will collapse
  When the user clicks on the heading of a section that contains a nested accordion
  Then the nested accordion will appear
    And the information surrounding the nested accordion will be visible (it is within the level of the first accordion)
    And the first section of the nested accordion will be expanded
    And all other sections of the nested accordion will be collapsed
  When a user clicks on the section heading for a collapsed section of the nested accordion
  Then that section will expand within the expanded first level accordion
  When a user clicks on the section heading for any expanded section of the nested accordion
  Then that section will collapse within the expanded first level accordion
  When a user clicks on multiple collapsed sections within the nested accordion sequentially
  Then the clicked on nested section will expand
    And the previously expanded nested section will collapse
  When a user clicks on the section heading for the expanded first level accordion that contains the nested accordion
  Then the section will collapse
  When the user reclicks on the same section heading of the now collapsed first level accordion that contains the nested accordion
  Then the section will expand with the nested accordion visible
    And the first section of the nested accordion will be expanded
    And the other sections of the nested accordion will be collapsed
```

### PR DESCRIPTION
**Pull request by arcepaul**
Closes #1468

Accordion example page: https://designsystem-dev.cancer.gov/pr-1549/example-site/example-pages/accordion.html

### CODE REVIEW

**Comment by olitharp-nci** [comment]
As the component work began before some of these questions in the technical discovery were completed, I'll copy down the developer decisions here:

> openSections - array - Maybe. Defaults to [1].
“maybe”

---

If a user adds:
`<div class=usa-accordion data-open-sections=1>`

it will act exactly the same as not adding data-open-sections.

But if a user adds
`<div class=usa-accordion data-open-sections=2>`

it will open the second section and not the first section.

If the user has enabled multiselect:
`<div class=usa-accordion data-allow-multiple=true data-open-sections=1>`

it will again only open the first one, data-open-sections=1 is redundant.

But if they make it a list such as:
`<div class=usa-accordion data-allow-multiple=true data-open-sections=1,2,3,4...n>`

it will open anything in the list.

Please note:
1. We're starting the list with index of 1, not 0.
2. If a user adds a list of sections, without enabling multiselect, throw a console warning, go back to the default setting of only opening the first section.

**Comment by dcvijanovic1k** [comment]
Looks good - approved! Tested FF/Chrome/Safari

**Comment by adrianacastaneda** [comment]
looks good! Thanks!

**Review by sarinapadilla — APPROVED** [review]
Looks great!

**Comment by bennettcc** [comment]
Passed Federal signoff during 3/19 demo - Anna, Alex, Jorge approved

**Review by bennettcc — APPROVED** [review]

**Comment by bennettcc** [comment]
Passed by product on 3/19 (Sarina, Cam) - adding the checkmark

**Review by olitharp-nci — APPROVED** [review]

**Pull request merged**
